### ISSUE TITLE
Example configuration on Synapse Discord is invalid

### ISSUE THREAD

**Issue by cubuzz** [TheVoidNebula/Sizes#1]
The example config on a discord showcasing the plugin should be valid. As of right now, it is not. 

```yaml
isEnabled: true # Should the Plugin be enabled?

minimumSize: true # What is the minimum size a player can spawn with?

maximumSize: 50 # What is the maximum size a player can spawn with?

minimumVolume: 300 # What is the minimum width a player can spawn with?

maximumVolume: true # What is the maximum width a player can spawn with?
```

Both minimumSize and maximumVolume are set to true, which is not a float. Also, the example values on Discord (50, 300) are too large and will cause the anticheat to kill you as soon as you spawn.
